### ISSUE TITLE
clock_v2.kicad_pcb is dummy file

### ISSUE THREAD

**Issue by Berzerkula** [adrienkohlbecker/6502#1]
the clock v2 kicad pcb is a Kicad v4 dummy file. Is the proper pcb available?

**Comment by adrienkohlbecker** [comment]
Hi! Thanks for raising an issue and sorry for the late reply. I have recently cleaned up this repository and moved the clock to its own place: https://github.com/adrienkohlbecker/6502_clock There you should find everything you need!

**Comment by adrienkohlbecker** [comment]
I just realized you were talking about clock_v2. That was an experiment I have since deleted. However, it evolved into the current clock of my BB816 project here https://github.com/adrienkohlbecker/BB816 (still no pcb for now though).
